### ISSUE TITLE
WoW Classic LUA errors

### ISSUE THREAD

**Issue by jayesquire** [DennisWG/BetterAlign#1]
#1:
Message: [string "BetterAlignOptionsPanel:OnLoad"]:1: attempt to index global 'this' (a nil value)
Time: Sun Jun  2 01:55:14 2019
Count: 1
Stack: [string "BetterAlignOptionsPanel:OnLoad"]:1: attempt to index global 'this' (a nil value)
[string "*:OnLoad"]:1: in function <[string "*:OnLoad"]:1>

Locals: self = BetterAlignOptionsPanel {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'this' (a nil value)"

#2:
Message: [string "BetterAlignGridSize:OnShow"]:1: attempt to index global 'this' (a nil value)
Time: Sun Jun  2 01:56:33 2019
Count: 2
Stack: [string "BetterAlignGridSize:OnShow"]:1: attempt to index global 'this' (a nil value)
[string "*:OnShow"]:1: in function <[string "*:OnShow"]:1>
[C]: in function `Show'
Interface\AddOns\BetterAlign\BetterAlign.lua:245: in function `?'
Interface\FrameXML\ChatFrame.lua:4642: in function `ChatEdit_ParseText'
Interface\FrameXML\ChatFrame.lua:4303: in function `ChatEdit_SendText'
Interface\FrameXML\ChatFrame.lua:4339: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals: self = BetterAlignGridSize {
 0 = <userdata>
 type = 3
 Thumb = BetterAlignGridSizeThumb {
 }
 Text = BetterAlignGridSizeText {
 }
 High = BetterAlignGridSizeHigh {
 }
 Low = BetterAlignGridSizeLow {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'this' (a nil value)"

#3:
Message: [string "MoveFrame0:OnLoad"]:1: attempt to index global 'this' (a nil value)
Time: Sun Jun  2 02:02:26 2019
Count: 1
Stack: [string "MoveFrame0:OnLoad"]:1: attempt to index global 'this' (a nil value)
[string "*:OnLoad"]:1: in function <[string "*:OnLoad"]:1>
[C]: in function `CreateFrame'
Interface\AddOns\BetterAlign\BetterAlign.lua:101: in function `AddButton_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals: self = MoveFrame0 {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'this' (a nil value)"

#4:
Message: [string "MoveFrame1:OnLoad"]:1: attempt to index global 'this' (a nil value)
Time: Sun Jun  2 02:02:26 2019
Count: 1
Stack: [string "MoveFrame1:OnLoad"]:1: attempt to index global 'this' (a nil value)
[string "*:OnLoad"]:1: in function <[string "*:OnLoad"]:1>
[C]: in function `CreateFrame'
Interface\AddOns\BetterAlign\BetterAlign.lua:102: in function `AddButton_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals: self = MoveFrame1 {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'this' (a nil value)"

**Comment by DennisWG** [comment]
I assume this is from the Classic Beta client?

**Comment by jayesquire** [comment]
Yes sir. This was the "Beta: World of Warcraft Classic" selection in the Battle.net client.

**Comment by DennisWG** [comment]
Up until my reply yesterday this Addon wasn't working for Classic Beta. However, this prompted me to download a Sandbox (no Beta invite :( ) and experiment a little bit.

You should now be able to use the Addon!

See: https://github.com/DennisWG/BetterAlign/releases/tag/1.0.0
